# Model hyper parameters
hyper_params:
  neural__batch_size:
    - 16
    - 32
    - 64
  neural__epochs:
    - 5
    - 10
    - 7
  neural__optimizer:
    - adam
    - sgd
    - rmsprop
  neural__model__loss:
    - sparse_categorical_crossentropy
